//! Autogenerated weights for pallet_relay_coordination
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-01 (Y/M/D)
//!
//! For now, using simple estimates. Run benchmarks to generate actual weights.

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_relay_coordination.
pub trait WeightInfo {
    fn volunteer_as_relay() -> Weight;
    fn deregister_relay() -> Weight;
    fn report_relay_metrics() -> Weight;
}

/// Weights for pallet_relay_coordination using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn volunteer_as_relay() -> Weight {
        // Includes: reserve stake, storage writes for relay info, region mapping
        Weight::from_parts(80_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    fn deregister_relay() -> Weight {
        // Includes: unreserve stake, storage removals
        Weight::from_parts(60_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    fn report_relay_metrics() -> Weight {
        // Includes: metric updates, potential slashing logic
        Weight::from_parts(70_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
}

// For tests
impl WeightInfo for () {
    fn volunteer_as_relay() -> Weight {
        Weight::from_parts(80_000_000, 0)
    }

    fn deregister_relay() -> Weight {
        Weight::from_parts(60_000_000, 0)
    }

    fn report_relay_metrics() -> Weight {
        Weight::from_parts(70_000_000, 0)
    }
}
