//! Autogenerated weights for pallet_topological_coherence
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI
//! DATE: 2026-01-06
//!
//! These are estimated weights based on storage operations.
//! Run benchmarks to generate actual weights for production.

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_topological_coherence.
pub trait WeightInfo {
    fn register_entity() -> Weight;
    fn submit_transition() -> Weight;
    fn update_config() -> Weight;
    fn unflag_account() -> Weight;
}

/// Weights for pallet_topological_coherence using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: TopologicalCoherence GlobalConfig (r:1 w:0)
    /// Storage: TopologicalCoherence Trackers (r:1 w:1)
    /// Storage: TopologicalCoherence EntityCount (r:1 w:1)
    fn register_entity() -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    /// Storage: TopologicalCoherence Flagged (r:1 w:0)
    /// Storage: TopologicalCoherence Trackers (r:1 w:1)
    /// Storage: TopologicalCoherence GlobalConfig (r:1 w:0)
    /// Proof Size: Worst case includes flagging account
    fn submit_transition() -> Weight {
        Weight::from_parts(35_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    /// Storage: TopologicalCoherence GlobalConfig (r:0 w:1)
    fn update_config() -> Weight {
        Weight::from_parts(10_000_000, 0)
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: TopologicalCoherence Flagged (r:0 w:1)
    fn unflag_account() -> Weight {
        Weight::from_parts(10_000_000, 0)
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

/// For tests and when WeightInfo is not configured
impl WeightInfo for () {
    fn register_entity() -> Weight {
        Weight::from_parts(25_000_000, 0)
    }

    fn submit_transition() -> Weight {
        Weight::from_parts(35_000_000, 0)
    }

    fn update_config() -> Weight {
        Weight::from_parts(10_000_000, 0)
    }

    fn unflag_account() -> Weight {
        Weight::from_parts(10_000_000, 0)
    }
}
