//! Autogenerated weights for pallet_validator_entropy
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-01 (Y/M/D)
//!
//! For now, using simple estimates. Run benchmarks to generate actual weights.

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_validator_entropy.
pub trait WeightInfo {
    fn register_entropy_config() -> Weight;
    fn remove_entropy_config() -> Weight;
}

/// Weights for pallet_validator_entropy using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn register_entropy_config() -> Weight {
        Weight::from_parts(50_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    fn remove_entropy_config() -> Weight {
        Weight::from_parts(30_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(3))
    }
}

// For tests
impl WeightInfo for () {
    fn register_entropy_config() -> Weight {
        Weight::from_parts(50_000_000, 0)
    }

    fn remove_entropy_config() -> Weight {
        Weight::from_parts(30_000_000, 0)
    }
}
